### ISSUE TITLE
toolpaths completely inside tabs must be deleted (Copied from file)

### ISSUE THREAD

**Issue by Siemenc** [fellesverkstedet/Bark-beetle-parametric-toolpaths#14]
Bug copied from file

**Comment by Siemenc** [comment]
fixed, but not properly tested,difficult to replicate problem (copied from file)

**Comment by Siemenc** [comment]
I can't seem to replicate this either so I'm closing for now. Post an example file here in case it happens again.

**Comment by JensDyvik** [comment]
Thank you for moving this bug report to github issues. I am also not able to replicate this an I think maybe I solved this bug some time ago.

It seems that if a toolpath is entirely inside a tab box, it will also be left out of tab cleanup. I think this ok behavior and not a bug.
