### ISSUE TITLE
pockets offset overshoot (copied from file)

### ISSUE THREAD

**Issue by Siemenc** [fellesverkstedet/Bark-beetle-parametric-toolpaths#18]
Bug copied from file

**Comment by Siemenc** [comment]
Example file for this?

**Comment by Siemenc** [comment]
Is it for examples like this? Because I found the error that causes this and fixed it. As soon as I got my github up and running I'll commit the updated version

![image](https://user-images.githubusercontent.com/10272127/36043289-1f832850-0dcf-11e8-9747-970192f612fe.png)

**Comment by Siemenc** [comment]
Github up and running. Committed latest pocket component which solves this.

**Comment by JensDyvik** [comment]
Awesome to have this fixed. Thank you very much. The fix has been included in the main CNC milling example in the latest development folder: https://github.com/fellesverkstedet/Bark-beetle-parametric-toolpaths/commit/b1dd65f60118ba676e5350a7cde896db4f392525
