### ISSUE TITLE
Inch conversion slows down calculating

### ISSUE THREAD

**Issue by Siemenc** [fellesverkstedet/Bark-beetle-parametric-toolpaths#2]
In postprocessor inch conversion slows down the definition - Remove this feature?
[Link to component](https://github.com/fellesverkstedet/Bark-beetle-parametric-toolpaths/blob/master/Bark%20beetle%20components/CNC%20milling%20PostProcessor.ghuser)

**Comment by Siemenc** [comment]
![image](https://user-images.githubusercontent.com/10272127/35772755-b6a8de04-0943-11e8-85aa-5234bdb8343d.png)

**Comment by Siemenc** [comment]
I wanted to fix this but I'm not sure which one is the latest update on the postprocessor component: See #43

**Comment by JensDyvik** [comment]
Fixed with new version of the CNC milling post processor. The inch conversion option has been removed. Much safer anyway since the inch conversion was only a test and not reliably implemented.

Very interspersing that a simple dividing by 1 operation could create so much calculation time.
