### ISSUE TITLE
fix pocket raster (copied from file)

### ISSUE THREAD

**Issue by Siemenc** [fellesverkstedet/Bark-beetle-parametric-toolpaths#25]
Bug copied from file

**Comment by Siemenc** [comment]
Is this related to the problem that was solved in [this issue](https://github.com/fellesverkstedet/Bark-beetle-parametric-toolpaths/issues/23)?

**Comment by Siemenc** [comment]
I think I've fixed the pocket raster, if this is the problem?
![image](https://user-images.githubusercontent.com/10272127/36094561-0ff723ec-0fef-11e8-9bbe-dc5c17216c4a.png)

**Comment by Siemenc** [comment]
As soon as I committed the new pocket component I'll be closing this. There's still some room for improvement on the offset rastering but as shown in issues #41 and #39 most of it has been improved.

**Comment by JensDyvik** [comment]
Awesome awesome. The bug description was aimed at general improvement of the mastering logic, which it seems you have contributed a lot to. Is now included in the latest example file
