### ISSUE TITLE
Error when opening Template.3dm

### ISSUE THREAD

**Issue by Siemenc** [fellesverkstedet/Bark-beetle-parametric-toolpaths#3]
Missing image files
![image](https://user-images.githubusercontent.com/10272127/35771985-332873c6-0936-11e8-9bfc-3ec8215c431e.png)

**Comment by Siemenc** [comment]
Committed an updated version without this error.

**Comment by JensDyvik** [comment]
Great. Thank you very much for the fix. Very nice to weed out annoying error messages
