### ISSUE TITLE
Pocket with curves inside that form an island get recognized as a curve inside a curve

### ISSUE THREAD

**Issue by Siemenc** [fellesverkstedet/Bark-beetle-parametric-toolpaths#39]
See example below: Area with X should create a pocket as well. But in current logic it defines it as an area inside an area and therefore skipping it.
![image](https://user-images.githubusercontent.com/10272127/36094670-70a2d38a-0fef-11e8-95f7-db0d4e03c618.png)

**Comment by Siemenc** [comment]
Here's another example of issues with curves inside inside. This works well: 
![image](https://user-images.githubusercontent.com/10272127/36287476-730333ea-12b5-11e8-83df-a23fcd5d15a8.png)
Now if I add these curves on the bottom right, it messes up the inside inside.
![image](https://user-images.githubusercontent.com/10272127/36287517-b1e0ffca-12b5-11e8-9267-809d261c60f7.png)

**Comment by Siemenc** [comment]
With sorting out the offset component as described in #41  I also fixed these issues. Very satisfying to see these special cases being calculated. Even a tiny bit faster than the old offset component![image](https://user-images.githubusercontent.com/10272127/36570593-0ac4970a-1833-11e8-9208-3eb6ec03d51d.png)

**Comment by JensDyvik** [comment]
Greeeeeeeeeeeeeeat!   As mentioned in the other issues, the improved pocket function is now included in the latest CNC milling example. https://github.com/fellesverkstedet/Bark-beetle-parametric-toolpaths/commit/b1dd65f60118ba676e5350a7cde896db4f392525
