### ISSUE TITLE
Enhancing toolpath preview: direction of cutting

### ISSUE THREAD

**Issue by Siemenc** [fellesverkstedet/Bark-beetle-parametric-toolpaths#4]
It would be nice if we can somehow see which direction it's going to cut. Maybe a small triangle at the start and end point of the toolpath?

**Comment by JensDyvik** [comment]
Nice. Added this in the latest CNC milling example with the Vector preview function. Seems to work well:
https://github.com/fellesverkstedet/Bark-beetle-parametric-toolpaths/commit/16ac5d37f695df213bd08f93fc9eb13710d35a9a

**Comment by Siemenc** [comment]
Looks great! Nice and simple solution.
