### ISSUE TITLE
Firefly is needed when using the postprocessor component from the Bark beetle tab

### ISSUE THREAD

**Issue by Siemenc** [fellesverkstedet/Bark-beetle-parametric-toolpaths#43]
![image](https://user-images.githubusercontent.com/10272127/36607675-9df74dbc-18c7-11e8-864a-b4cb426abc27.png)
But strangely enough this doesn't happen when opening the "Bark beetle cnc milling" document. Does the latter one contain a different version? Which one is up to date?

**Comment by JensDyvik** [comment]
Fixed with new version of the CNC milling post processor. The post processor no longer use the Constrain function from Firefly
