### ISSUE TITLE
Potential speed enhancement: an easier+quicker align curves in same direction

### ISSUE THREAD

**Issue by Siemenc** [fellesverkstedet/Bark-beetle-parametric-toolpaths#49]
I came across this solution for making curves go the same direction. Seems to speed up things a lot (x 100 in example below) since there's no need for offset.
![image](https://user-images.githubusercontent.com/10272127/48146768-0b852300-e2b6-11e8-9c34-e2d93cad3594.png)

**Comment by JensDyvik** [comment]
Exciting. Don't you need to know whether a curve is going in a climb or conventional direction before you decide to flip? I havent found a good way to analyze if a curve is climb or conventional. Also note that curves inside a curve needs to go in the other direction than the outer curve since they are inside cuts

**Comment by Siemenc** [comment]
_Don't you need to know whether a curve is going in a climb or conventional direction before you decide to flip?_
Yes, that's what the circle does. Flip curve has an input G which is a guide curve to check against whether the input in C is in the same direction or not. If the direction is different it switches it to match the same direction.

Also just for clarity: It doesn't speed up the whole component by 100x. The solution above just makes a part of the component 100x faster.

_Also note that curves inside a curve needs to go in the other direction than the outer curve since they are inside cuts_
Yep, that's what happens after this step inside the cutout (and other) component . It basically just would replace this:
![image](https://user-images.githubusercontent.com/10272127/48165482-04760900-e2e6-11e8-8a79-31d05c1bb8c6.png)

**Comment by JensDyvik** [comment]
Fantastic. Very nice solution. This combined with creating boundary surfaces from cutout and pocket curves to find curves inside curves will be a great combo
