### ISSUE TITLE
Sorting by control points / changing control points

### ISSUE THREAD

**Issue by Siemenc** [fellesverkstedet/Bark-beetle-parametric-toolpaths#60]
Got some suggestions from somebody on the Rhino forum, which nice explanatory gifs
https://discourse.mcneel.com/t/i-wish-there-was-an-entry-level-cam-solution-for-rhino3d/64135/87?u=siemen

Could be good to have control over where the startpoint of each curve is. Might be for very special cases where it's necessary (like pieces that are positioned close to each other) but would be nice to have for those cases.
Sorting by control points shouldn't be that hard to implement after that.

**Comment by Siemenc** [comment]
This has been implemented in the latest commit.

![image](https://user-images.githubusercontent.com/10272127/83333311-2eb06280-a2a0-11ea-9c09-9551573c7154.png)

![image](https://user-images.githubusercontent.com/10272127/83333291-15a7b180-a2a0-11ea-9efe-a9c556334f4f.png)

**Comment by JensDyvik** [comment]
Absolutely awesome with sorting implemented and the menu options!
