### ISSUE TITLE
List matching bug in 3D mill

### ISSUE THREAD

**Issue by Siemenc** [fellesverkstedet/Bark-beetle-parametric-toolpaths#77]
Was getting some issues with milling a quite easy surface today, 1 of the 2 problems I found was that something was off with list matching causing unnecessary jogging and less efficient toolpaths. It was an easy fix once I found the problem. I'll upload version 1.01, which fixes this, later.
Before:
![image](https://user-images.githubusercontent.com/10272127/110958686-421f4c80-834d-11eb-88c8-8b928a68606b.png)

After
![image](https://user-images.githubusercontent.com/10272127/110959099-a6daa700-834d-11eb-8258-b0c51249da59.png)

**Comment by Siemenc** [comment]
Looks like I was behind on the latest version. :-) Will upload it as 1.02 Beta 2, as discussed with @JensDyvik

**Comment by JensDyvik** [comment]
Awesome. Thank you for fixing Siemen! I was not aware of this list management error. We had so many list management bugs from gh in rhino5 to gh in rhino6. Luckily it seems that list management has not changed in rhino7.
